spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dio-database?currentSchema=public
    username: postgres
    password: 368091
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
        default_schema: public
